config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'items' => 'public/items#index'
  get 'items/:id' => 'public/items#show', as: :item

  scope :customers do

 devise_for :customers, skip: :all
  devise_scope :customer do
    get 'sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/' => 'public/registrations#create', as: :customer_registration
    get 'sign_in' => 'public/sessions#new', as: :new_customer_session
    post 'sign_in' => 'public/sessions#create', as: :customer_session
    delete 'sign_out' => 'public/sessions#destroy', as: :destroy_customer_session
  end

  get 'my_page' => 'public/customers#show'
  get 'edit' => 'public/customers#edit'
  patch '/' => 'public/customers#update'
  get 'unsubscribe' => 'public/customers#unsubscribe'
  patch 'withdraw' => 'public/customers#withdraw'

 end

  get 'cart_items' => 'public/cart_items#index', as: :cart_items
  patch 'cart_items/:id' => 'public/cart_items#update', as: :cart_item_update
  delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: :cart_item_destroy_all
  delete 'cart_items/:id' => 'public/cart_items#destroy', as: :cart_item_destroy
  post 'cart_items' => 'public/cart_items#create', as: :cart_item_create

  get 'orders/new' => 'public/orders#new', as: :orders_new
  post 'orders/confirm' => 'public/orders#confirm', as: :orders_confirm
  get 'orders/complete' => 'public/orders#complete', as: :orders_complete
  post 'orders' => 'public/orders#create', as: :orders_create
  get 'orders' => 'public/orders#index', as: :orders_index
  get 'orders/:id' => 'public/orders#show', as: :orders_show
  delete '/orders/destroy_all' => 'public/orders#destroy_all', as: :order_destroy_all

  get 'addresses' => 'public/addresses#index', as: :addresses
  get 'addresses/:id/edit' => 'public/addresses#edit', as: :edit_address
  post 'addresses' => 'public/addresses#create', as: :address_create
  patch 'addresses/:id' => 'public/addresses#update', as: :address_update
  delete 'addresses/:id' => 'public/addresses#destroy', as: :address

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
    post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session

  end

  namespace :admin do

  get '/' => 'homes#top'

  resources :items, only: [:index, :new, :show, :edit]
  post 'items' => 'items#create', as: 'item_create'
  patch 'items/:id' => 'items#update', as: 'item_update'

  get 'genres' => 'genres#index'
  post 'genres' => 'genres#create'
  get 'genres/:id/edit' => 'genres#edit', as: 'genre_show_edit'
  patch 'genres/:id' => 'genres#update', as: 'genre_update'

  resources :customers, only: [:index, :show, :edit]
  patch 'customers/:id' => 'customers#update', as: 'customer_update'

  get 'orders/:id' => 'orders#show', as: 'orders_show'
  patch 'orders/:id' => 'orders#update', as: 'orders_update'

  patch 'order_details/:id' => 'order_details#update', as: 'order_detail_update'

  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == true)
  end

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to admin_customers_path
    else
      render :edit
    end
  end

  def customer_params
  params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted, :email)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-5">
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-11">
      <span class="px-3 h4 bg-light text-dark"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-11 px-4">
      <% if @customer.errors.any? %>
        <%#= @item.errors.count %>
        <% @customer.errors.full_messages.each do |message| %>
         <div>
          <li><font color="red"><%= message %></font></li>
         </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= form_with model: @customer, url: admin_customer_update_path, local:true do |f| %>
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-11">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td width="140">会員ID</td><td width="160"><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td><td><%= f.text_field :last_name %></td><td><span class="px-3"><%= f.text_field :first_name %></span></td>
          </tr>
          <tr>
            <td>フリガナ</td><td><%= f.text_field :last_name_kana %></td><td><span class="px-3"><%= f.text_field :first_name_kana %></span></td>
          </tr>
          <tr>
            <td>郵便番号</td><td><%= f.text_field :postal_code %></td>
          </tr>
        </tbody>
      </table>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td width="140">住所</td><td><%= f.text_field :address, class: 'w-75' %></td>
          </tr>
        </tbody>
      </table>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td width="140">電話番号</td><td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td><td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%= f.radio_button :is_deleted, true %><%= f.label :is_deleted, '有効', value: true %>
              <span class="px-2"><%= f.radio_button :is_deleted, false %><%= f.label :is_deleted, '退会', value: false %></span>
            </td>
          </tr>
          <tr>
            <td></td><td><%= f.submit '変更を保存', class: 'btn btn-success' %></td>
          </tr>
        </tbody>
      </table>
  <% end %>
    </div>
  </div>

</div>

app/views/admin/customers/index.html.erb
<div class="container mt-5">
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-11">
      <span class="px-3 h4 bg-light text-dark">会員⼀覧</span>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-8">
      <table class="table border-bottom">
          <tr class="bg-light">
            <td>会員ID</td>
            <td>氏名</td>
            <td>メールアドレス</td>
            <td>ステータス</td>
          </tr>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to admin_customer_path(customer.id) do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted %>
            <font color="green">有効</font>
                <% else %>
            <font color="silver">退会</font>
                <% end %>
            </td>
          </tr>
        <% end %>
        </table>
      </div>
    <div class="col-lg-2">
    </div>
  </div>
  <div class="pagination justify-content-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-5">
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-11">
      <span class="px-3 h4 bg-light text-dark"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-7">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td width="140">会員ID</td><td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td><td><%= @customer.last_name %><%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td><td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td><td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td><td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td><td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td><td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><% if @customer.is_deleted %>
            <font color="green">有効</font>
                <% else %>
            <font color="silver">退会</font>
                <% end %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success' %>
            <span class="ml-5"><%= link_to "注⽂履歴⼀覧を⾒る", admin_path, class: 'btn btn-primary' %>
            </span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-lg-4">
    </div>
  </div>
</div>