config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'items' => 'public/items#index'
  get 'items/:id' => 'public/items#show', as: :item

  scope :customers do

 devise_for :customers, skip: :all
  devise_scope :customer do
    get 'sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/' => 'public/registrations#create', as: :customer_registration
    get 'sign_in' => 'public/sessions#new', as: :new_customer_session
    post 'sign_in' => 'public/sessions#create', as: :customer_session
    delete 'sign_out' => 'public/sessions#destroy', as: :destroy_customer_session
  end

  get 'my_page' => 'public/customers#show'
  get 'edit' => 'public/customers#edit'
  patch '/' => 'public/customers#update'
  get 'unsubscribe' => 'public/customers#unsubscribe'
  patch 'withdraw' => 'public/customers#withdraw'

 end

  get 'cart_items' => 'public/cart_items#index', as: :cart_items
  patch 'cart_items/:id' => 'public/cart_items#update', as: :cart_item_update
  delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: :cart_item_destroy_all
  delete 'cart_items/:id' => 'public/cart_items#destroy', as: :cart_item_destroy
  post 'cart_items' => 'public/cart_items#create', as: :cart_item_create

  get 'orders/new' => 'public/orders#new', as: :orders_new
  post 'orders/confirm' => 'public/orders#confirm', as: :orders_confirm
  get 'orders/complete' => 'public/orders#complete', as: :orders_complete
  post 'orders' => 'public/orders#create', as: :orders_create
  get 'orders' => 'public/orders#index', as: :orders_index
  get 'orders/:id' => 'public/orders#show', as: :orders_show
  delete '/orders/destroy_all' => 'public/orders#destroy_all', as: :order_destroy_all

  get 'addresses' => 'public/addresses#index', as: :addresses
  get 'addresses/:id/edit' => 'public/addresses#edit', as: :edit_address
  post 'addresses' => 'public/addresses#create', as: :address_create
  patch 'addresses/:id' => 'public/addresses#update', as: :address_update
  delete 'addresses/:id' => 'public/addresses#destroy', as: :address

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
    post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session

  end

  namespace :admin do

  get '/' => 'homes#top'

  resources :items, only: [:index, :new, :show, :edit]
  post 'items' => 'items#create', as: 'item_create'
  patch 'items/:id' => 'items#update', as: 'item_update'

  get 'genres' => 'genres#index'
  post 'genres' => 'genres#create'
  get 'genres/:id/edit' => 'genres#edit', as: 'genre_show_edit'
  patch 'genres/:id' => 'genres#update', as: 'genre_update'

  resources :customers, only: [:index, :show, :edit]
  patch 'customers/:id' => 'customers#update', as: 'customer_update'

  get 'orders/:id' => 'orders#show', as: 'orders_show'
  patch 'orders/:id' => 'orders#update', as: 'orders_update'

  patch 'order_details/:id' => 'order_details#update', as: 'order_detail_update'

  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: [:クレジットカード, :銀行振込]
  enum status: { 入金待ち: 0, 入金確認: 1, 制作中: 2, 発送待ち: 3, 発送済: 4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.new(order_params)
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:status] == "入金確認" then
      @order = Order.find(params[:id])
      @order_details = @order.order_details
      @order_details.update( making_status: "制作待ち")
      redirect_to admin_orders_show_path(@order.id)
    else
      redirect_to admin_orders_show_path(@order.id)
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container mt-5">
  <div class="row mt-3">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-11">
      <span class="px-3 h4 bg-light text-dark">注⽂履歴詳細</span>
    </div>
  </div>
<table class="table table-borderless">
  <tbody>
    <tr>
      <th width="140">購入者</th><td><%= link_to admin_customer_path(@order.customer.id) do %><%= @order.customer.last_name %><%= @order.customer.first_name %><% end %></td>
    </tr>
    <tr>
      <th>注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th><td>〒<%= @order.postal_code %><span class="px-2"><%= @order.address %></span></td>
    </tr>
    <tr>
      <th></th><td><%= @order.name %></td>
    </tr>
    <tr>
      <th>支払方法</th><td><%= @order.payment_method %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>

      <td><%= form_with model: @order, url: admin_orders_update_path(@order.id), local:true do |f| %>
          <%= f.select :status, Order.statuses.keys.to_a, {} %>
          <span class="px-4"><%= f.submit '更新', class: 'btn btn-success btn-sm' %><% end %></span>
      </td>
    </tr>
  </tbody>

</table>
  <div class="row mt-3">
    <div class="col-lg-9">
      <table class="table table-borderless border-top border-bottom">
        <tr class="bg-light">
          <th>商品名</th>
          <th class="text-center">単価(税込)</th>
          <th class="text-center">数量</th>
          <th class="text-center">小計</th>
          <th class="px-5">制作ステータス</th>
        </tr>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td class="align-middle" width="170"><%= order_detail.item.name %></td>
          <td class="align-middle text-center" width="120"><%= (order_detail.item.price * 1.1).floor %></td>
          <td class="align-middle text-center" width="70"><%= order_detail.amount %></td>
          <td class="align-middle text-center" width="70"><%= (order_detail.item.price * 1.1).floor * order_detail.amount %></td>
          <%#= f.select :production_status, OrderedItem.production_statuses.keys, :selected=>OrderedItem.production_statuses[ordered_item.production_status] %>
          <td class="align-middle text-center" width="200"><%= form_with model: order_detail, url: admin_order_detail_update_path(order_detail.id), method: :patch, local:true do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a, {} %>
            <span class="px-4"><%= f.submit '更新', class: 'btn btn-success' %><% end %></span>
          </td>
        </tr>
      <% end %>
      </table>
    </div>
    <div class="col-lg-3 d-flex align-items-end">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th width="120">商品合計</th><td><%= @order.total_payment - @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <th>送料</th><td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th><td><%= @order.total_payment %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>