config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'items' => 'public/items#index'
  get 'items/:id' => 'public/items#show', as: :item

  scope :customers do

 devise_for :customers, skip: :all
  devise_scope :customer do
    get 'sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/' => 'public/registrations#create', as: :customer_registration
    get 'sign_in' => 'public/sessions#new', as: :new_customer_session
    post 'sign_in' => 'public/sessions#create', as: :customer_session
    delete 'sign_out' => 'public/sessions#destroy', as: :destroy_customer_session
  end

  get 'my_page' => 'public/customers#show'
  get 'edit' => 'public/customers#edit'
  patch '/' => 'public/customers#update'
  get 'unsubscribe' => 'public/customers#unsubscribe'
  patch 'withdraw' => 'public/customers#withdraw'

 end

  get 'cart_items' => 'public/cart_items#index', as: :cart_items
  patch 'cart_items/:id' => 'public/cart_items#update', as: :cart_item_update
  delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: :cart_item_destroy_all
  delete 'cart_items/:id' => 'public/cart_items#destroy', as: :cart_item_destroy
  post 'cart_items' => 'public/cart_items#create', as: :cart_item_create

  get 'orders/new' => 'public/orders#new', as: :orders_new
  post 'orders/confirm' => 'public/orders#confirm', as: :orders_confirm
  get 'orders/complete' => 'public/orders#complete', as: :orders_complete
  post 'orders' => 'public/orders#create', as: :orders_create
  get 'orders' => 'public/orders#index', as: :orders_index
  get 'orders/:id' => 'public/orders#show', as: :orders_show
  delete '/orders/destroy_all' => 'public/orders#destroy_all', as: :order_destroy_all

  get 'addresses' => 'public/addresses#index', as: :addresses
  get 'addresses/:id/edit' => 'public/addresses#edit', as: :edit_address
  post 'addresses' => 'public/addresses#create', as: :address_create
  patch 'addresses/:id' => 'public/addresses#update', as: :address_update
  delete 'addresses/:id' => 'public/addresses#destroy', as: :address

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
    post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session

  end

  namespace :admin do

  get '/' => 'homes#top'

  resources :items, only: [:index, :new, :show, :edit]
  post 'items' => 'items#create', as: 'item_create'
  patch 'items/:id' => 'items#update', as: 'item_update'

  get 'genres' => 'genres#index'
  post 'genres' => 'genres#create'
  get 'genres/:id/edit' => 'genres#edit', as: 'genre_show_edit'
  patch 'genres/:id' => 'genres#update', as: 'genre_update'

  resources :customers, only: [:index, :show, :edit]
  patch 'customers/:id' => 'customers#update', as: 'customer_update'

  get 'orders/:id' => 'orders#show', as: 'orders_show'
  patch 'orders/:id' => 'orders#update', as: 'orders_update'

  patch 'order_details/:id' => 'order_details#update', as: 'order_detail_update'

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
      <header class="shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class="navbar-brand p-2 border" href="/"><%= image_tag 'ケーキ.jpg', :size =>'70x50' %></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarnavDropdown">
              <ul class="navbar-nav ml-auto">
                  <% if customer_signed_in? %>
                    <p class="m-2 pr-5"><font color="green">ようこそ<%= current_customer.last_name %>さん!</font></p>
                    <li class="nav-item pr-2">
                      <%= link_to 'マイページ', my_page_path, class: "btn btn-outline-primary" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "商品一覧", items_path, class: "btn btn-outline-danger" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "カート", cart_items_path, class: "btn btn-outline-success" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-info" %>
                    </li>
                    <%= form_tag(items_path, :method => "get") do %>
                    <div class="input-group">
                    <%= text_field_tag :search, params[:search],:placeholder => "キーワードで検索　　　 \uf002", class: 'fa' %>
                    <% end %>
                    </div>

                  <% elsif admin_signed_in? %>
                    <li class="nav-item pr-2">
                      <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-danger" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-primary" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "注⽂履歴⼀覧", admin_path,class: "btn btn-outline-success" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-warning" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-info" %>
                    </li>
                      <%= form_tag(admin_items_path, :method => "get") do %>
                      <%= text_field_tag :search, params[:search],:placeholder => "キーワードで検索" %>
                      <%= button_tag type: 'submit', class: 'btn btn-outline-primary' do %><i class="fas fa-search"></i>
                      <% end %>
                      <% end %>
                  <% else %>

                    <li class="nav-item pr-2">
                      <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "商品一覧", items_path, class: "btn btn-outline-danger" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-success" %>
                    </li>
                    <li class="nav-item pr-2">
                      <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-primary" %>
                    </li>
                    <%= form_tag(items_path, :method => "get") do %>
                    <div class="input-group">
                    <%= text_field_tag :search, params[:search],:placeholder => "キーワードで検索" %>
                    <span class="input-group-btn"><%= button_tag type: 'submit', class: 'btn btn-link' do %><i class="fas fa-search">
                    <% end %></i></span></div>
                    <% end %>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <%= yield %>
  </body>
</html>